**Exercício 1: Estatísticas Descritivas**

Crie um array de 50 números inteiros aleatórios entre 1 e 100. Calcule e exiba a média, mediana, desvio padrão, valor máximo e valor mínimo.

In [10]:
import numpy as np  
array = np.random.randint(1, 101, 50)
media = np.mean(array)
mediana = np.median(array)
desvio_padrao = np.std(array)
valor_maximo = np.max(array)
valor_minimo = np.min(array)
print(f"Array: {array}")
print("\n")
print(f"Média: {media}")
print(f"Mediana: {mediana}")
print(f"Devio padrão: {desvio_padrao:.2f}")
print(f"Valor Máximo: {valor_maximo}")
print(f"Valor Mínimo: {valor_minimo}")


Array: [ 67  71  21   4  24  47  87   9   2  52  42  49  64  76  63  63  77  16
  61  17  77  68  15  38  72  69  25   9   7  47  14  86  75  72   5  18
  83  47  56  41  22  46   2  21  92  11 100  20  52  44]


Média: 44.92
Mediana: 47.0
Devio padrão: 27.88
Valor Máximo: 100
Valor Mínimo: 2


**Exercício 2: Operações com Matrizes**

Crie duas matrizes 3x3 de números inteiros aleatórios entre 1 e 10. Realize as operações de adição, subtração, multiplicação e divisão elemento por elemento entre as duas matrizes.

In [17]:
import numpy as np
matriz1 = np.random.randint(1, 11,(3, 3))
matriz2 = np.random.randint(1, 11,(3, 3))

soma = matriz1 + matriz2
subtracao = matriz1 - matriz2
multiplicacao = matriz1 * matriz2
divisao = matriz1 / matriz2
print(f"Matriz 1:\n {matriz1}")
print(f"Matriz 2:\n {matriz2}")
print(f"Soma:\n {soma}")
print(f"Subtração:\n {subtracao}")
print(f"Multiplicação:\n {multiplicacao}")
print(f"Divisão:\n {divisao}")


Matriz 1:
 [[ 6  3  3]
 [ 9  2  1]
 [10  7  9]]
Matriz 2:
 [[10  6  1]
 [ 6  9  1]
 [ 2  4 10]]
Soma:
 [[16  9  4]
 [15 11  2]
 [12 11 19]]
Subtração:
 [[-4 -3  2]
 [ 3 -7  0]
 [ 8  3 -1]]
Multiplicação:
 [[60 18  3]
 [54 18  1]
 [20 28 90]]
Divisão:
 [[0.6        0.5        3.        ]
 [1.5        0.22222222 1.        ]
 [5.         1.75       0.9       ]]


**Exercício 3: Operações de Agregação**

Crie uma matriz 4x4 de números inteiros aleatórios entre 1 e 20. Calcule e exiba a soma dos elementos para cada linha e para cada coluna.

In [19]:
import numpy as np
matriz = np.random.randint(1, 21,(4, 4))
soma_linhas = np.sum(matriz, axis=1)
soma_colunas = np.sum(matriz, axis=0)

print(f"Matriz:\n {matriz}")
print(f"Soma das linhas:\n {soma_linhas}")
print(f"Soma das colunas:\n {soma_colunas}")

Matriz:
 [[ 8 10  6 11]
 [15  2 11 12]
 [19 15  8  6]
 [15  1  9  3]]
Soma das linhas:
 [35 40 48 28]
Soma das colunas:
 [57 28 34 32]


**Exercício 4: Filtragem de Valores**

Crie um array de 30 números inteiros aleatórios entre 0 e 50. Encontre e exiba todos os valores que são maiores que 25.

In [20]:
import numpy as np
array = np.random.randint(0, 51, 30)
valores_maiores_25 = array[array > 25]
print(f"Array completo:\n {array}")
print(f"Valores maiores que 25:\n {valores_maiores_25}")

Array completo:
 [31 29 29 47  6  5 44 48 43 36 37 41  8 41 25 39  1 15 23 42 20 25  9 12
 32 30 34 17 21 25]
Valores maiores que 25:
 [31 29 29 47 44 48 43 36 37 41 41 39 42 32 30 34]


**Exercício 5: Criação e Manipulação de Arrays Multidimensionais**

Crie uma matriz 3x3x3 de números inteiros aleatórios entre 1 e 10. Calcule a soma total dos elementos e a soma cumulativa.

In [21]:
import numpy as np
matriz = np.random.randint(1, 11, (3, 3, 3))
soma_total = np.sum(matriz)
soma_cumulativa = np.cumsum(matriz)
print(f"Matriz original:\n {matriz}")
print(f"Soma total:\n {soma_total}")
print(f"Soma cumulativa:\n {soma_cumulativa}")

Matriz original:
 [[[ 3  2  8]
  [ 7  7  3]
  [ 4  8  5]]

 [[ 1  7  9]
  [10  4 10]
  [ 5  2 10]]

 [[ 5 10  5]
  [ 5  6 10]
  [ 7  5  2]]]
Soma total:
 160
Soma cumulativa:
 [  3   5  13  20  27  30  34  42  47  48  55  64  74  78  88  93  95 105
 110 120 125 130 136 146 153 158 160]
