**Exercício 1: Estatísticas Descritivas**

Crie um array de 50 números inteiros aleatórios entre 1 e 100. Calcule e exiba a média, mediana, desvio padrão, valor máximo e valor mínimo.

In [1]:
import numpy as np  
array = np.random.randint(1, 101, 50)
media = np.mean(array)
mediana = np.median(array)
desvio_padrao = np.std(array)
valor_maximo = np.max(array)
valor_minimo = np.min(array)
print(f"Array: {array}")
print("\n")
print(f"Média: {media}")
print(f"Mediana: {mediana}")
print(f"Devio padrão: {desvio_padrao:.2f}")
print(f"Valor Máximo: {valor_maximo}")
print(f"Valor Mínimo: {valor_minimo}")


Array: [ 59  40  56  19  11  25  44  35  61  76  50  71  17  75  38  63  84  78
  58  18  62  17  46  25  47  92  18  47  13  38  37  66  48  67  10  92
  69  62  10  19  14  58   6  70  19  79  90  35 100  40]


Média: 47.48
Mediana: 47.0
Devio padrão: 25.62
Valor Máximo: 100
Valor Mínimo: 6


**Exercício 2: Operações com Matrizes**

Crie duas matrizes 3x3 de números inteiros aleatórios entre 1 e 10. Realize as operações de adição, subtração, multiplicação e divisão elemento por elemento entre as duas matrizes.

In [2]:
import numpy as np
matriz1 = np.random.randint(1, 11,(3, 3))
matriz2 = np.random.randint(1, 11,(3, 3))

soma = matriz1 + matriz2
subtracao = matriz1 - matriz2
multiplicacao = matriz1 * matriz2
divisao = matriz1 / matriz2
print(f"Matriz 1:\n {matriz1}")
print(f"Matriz 2:\n {matriz2}")
print(f"Soma:\n {soma}")
print(f"Subtração:\n {subtracao}")
print(f"Multiplicação:\n {multiplicacao}")
print(f"Divisão:\n {divisao}")


Matriz 1:
 [[1 5 8]
 [7 1 2]
 [2 3 9]]
Matriz 2:
 [[4 1 8]
 [8 5 2]
 [4 5 3]]
Soma:
 [[ 5  6 16]
 [15  6  4]
 [ 6  8 12]]
Subtração:
 [[-3  4  0]
 [-1 -4  0]
 [-2 -2  6]]
Multiplicação:
 [[ 4  5 64]
 [56  5  4]
 [ 8 15 27]]
Divisão:
 [[0.25  5.    1.   ]
 [0.875 0.2   1.   ]
 [0.5   0.6   3.   ]]


**Exercício 3: Operações de Agregação**

Crie uma matriz 4x4 de números inteiros aleatórios entre 1 e 20. Calcule e exiba a soma dos elementos para cada linha e para cada coluna.

In [19]:
import numpy as np
matriz = np.random.randint(1, 21,(4, 4))
soma_linhas = np.sum(matriz, axis=1)
soma_colunas = np.sum(matriz, axis=0)

print(f"Matriz:\n {matriz}")
print(f"Soma das linhas:\n {soma_linhas}")
print(f"Soma das colunas:\n {soma_colunas}")

Matriz:
 [[ 8 10  6 11]
 [15  2 11 12]
 [19 15  8  6]
 [15  1  9  3]]
Soma das linhas:
 [35 40 48 28]
Soma das colunas:
 [57 28 34 32]


**Exercício 4: Filtragem de Valores**

Crie um array de 30 números inteiros aleatórios entre 0 e 50. Encontre e exiba todos os valores que são maiores que 25.

In [20]:
import numpy as np
array = np.random.randint(0, 51, 30)
valores_maiores_25 = array[array > 25]
print(f"Array completo:\n {array}")
print(f"Valores maiores que 25:\n {valores_maiores_25}")

Array completo:
 [31 29 29 47  6  5 44 48 43 36 37 41  8 41 25 39  1 15 23 42 20 25  9 12
 32 30 34 17 21 25]
Valores maiores que 25:
 [31 29 29 47 44 48 43 36 37 41 41 39 42 32 30 34]


**Exercício 5: Criação e Manipulação de Arrays Multidimensionais**

Crie uma matriz 3x3x3 de números inteiros aleatórios entre 1 e 10. Calcule a soma total dos elementos e a soma cumulativa.

In [21]:
import numpy as np
matriz = np.random.randint(1, 11, (3, 3, 3))
soma_total = np.sum(matriz)
soma_cumulativa = np.cumsum(matriz)
print(f"Matriz original:\n {matriz}")
print(f"Soma total:\n {soma_total}")
print(f"Soma cumulativa:\n {soma_cumulativa}")

Matriz original:
 [[[ 3  2  8]
  [ 7  7  3]
  [ 4  8  5]]

 [[ 1  7  9]
  [10  4 10]
  [ 5  2 10]]

 [[ 5 10  5]
  [ 5  6 10]
  [ 7  5  2]]]
Soma total:
 160
Soma cumulativa:
 [  3   5  13  20  27  30  34  42  47  48  55  64  74  78  88  93  95 105
 110 120 125 130 136 146 153 158 160]


In [4]:
import numpy as np
minha_lista = [6, 7, 0, 1.2, 10]
arr1 = np.array(minha_lista)
arr1

array([ 6. ,  7. ,  0. ,  1.2, 10. ])

In [5]:
import numpy as np
lista_de_listas = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(lista_de_listas)
arr2

array([[1, 2, 3],
       [4, 5, 6]])