**Exercício 1: Estatísticas Descritivas**

Crie um array de 50 números inteiros aleatórios entre 1 e 100. Calcule e exiba a média, mediana, desvio padrão, valor máximo e valor mínimo.

In [6]:
import numpy as np
array = np.random.randint(1, 101, 50)
media = np.mean(array)
mediana = np.median(array)
desvio_padrao = np.std(array)
valor_maximo = np.max(array)
valor_minimo = np.min(array)
print(f"Array: {array}")
print(f"A média dos valores é: {media}")
print(f"A mediana dos valores é: {mediana}")
print(f"O desvio padrão é: {desvio_padrao:.2f}")
print(f"O valor máximo é: {valor_maximo}")
print(f"O valor mínimo é: {valor_minimo}")



Array: [80 92 98 63  1 32 92 32 29 36 88 39 21 27 84 17 51 54 94 97 29 43  1 92
 73 36 34 76 10 97 25 20 80 49 70 52 63 40 43 75  4 72 95  2  2 46 67 84
 74 41]
A média dos valores é: 52.44
A mediana dos valores é: 50.0
O desvio padrão é: 29.96
O valor máximo é: 98
O valor mínimo é: 1


**Exercício 2: Operações com Matrizes**

Crie duas matrizes 3x3 de números inteiros aleatórios entre 1 e 10. Realize as operações de adição, subtração, multiplicação e divisão elemento por elemento entre as duas matrizes.

In [4]:
import numpy as np
matriz1 = np.random.randint(1, 11,(3,3))
matriz2 = np.random.randint(1, 11,(3,3))
soma = matriz1 + matriz2
multiplicacao = matriz1 * matriz2
subtracao = matriz1 - matriz2
divisao = matriz1 / matriz2
print(f"Matriz 1: {matriz1}\n")
print(f"Matriz 2: {matriz2}\n")
print(f"Soma: {soma}\n")
print(f"Subtração: {subtracao}\n")
print(f"Multiplicação: {multiplicacao}\n")
print(f"Divisão: {divisao}\n")


Matriz 1: [[5 5 9]
 [3 6 5]
 [4 4 4]]

Matriz 2: [[1 2 1]
 [8 9 8]
 [3 8 3]]

Soma: [[ 6  7 10]
 [11 15 13]
 [ 7 12  7]]

Subtração: [[ 4  3  8]
 [-5 -3 -3]
 [ 1 -4  1]]

Multiplicação: [[ 5 10  9]
 [24 54 40]
 [12 32 12]]

Divisão: [[5.         2.5        9.        ]
 [0.375      0.66666667 0.625     ]
 [1.33333333 0.5        1.33333333]]



**Exercício 3: Operações de Agregação**

Crie uma matriz 4x4 de números inteiros aleatórios entre 1 e 20. Calcule e exiba a soma dos elementos para cada linha e para cada coluna.

In [10]:
import numpy as np
matriz = np.random.randint(1, 21,(4, 4))
soma_linhas = np.sum(matriz, axis=1)
soma_colunas = np.sum(matriz, axis=0)
print(f"Matriz:\n {matriz}")
print(f"Soma das linhas:\n {soma_linhas}")
print(f"Soma das colunas:\n {soma_colunas}")

Matriz:
 [[10 13 16 10]
 [18  1 20 14]
 [ 4 12  4 13]
 [ 7 15  9  2]]
Soma das linhas:
 [49 53 33 33]
Soma das colunas:
 [39 41 49 39]


**Exercício 4: Filtragem de Valores**

Crie um array de 30 números inteiros aleatórios entre 0 e 50. Encontre e exiba todos os valores que são maiores que 25.

In [15]:
import numpy as np
array = np.random.randint(0, 51, 30)
valores_maiores_25 = array[array > 25]
print(f"Array:\n {array}")
print(f"Valores maiores que 25:\n {valores_maiores_25}")

Array:
 [10 40 22 47 42 42 11 30 39 16 22 26  9 40 41 27  6 40 35 28 49  3  7 38
 33 25 42 37 15 34]
Valores maiores que 25:
 [40 47 42 42 30 39 26 40 41 27 40 35 28 49 38 33 42 37 34]


**Exercício 5: Criação e Manipulação de Arrays Multidimensionais**

Crie uma matriz 3x3x3 de números inteiros aleatórios entre 1 e 10. Calcule a soma total dos elementos e a soma cumulativa.

In [19]:
import numpy as np
matriz3 = np.random.randint(1, 11, (3, 3, 3))
soma_total = np.sum(matriz3)
soma_acumulativa = np.cumsum(matriz3)
print(f"Matriz:\n {matriz3}")
print(f"Soma Total:\n {soma_total}")
print(f"Soma acumulativa:\n {soma_acumulativa}")

Matriz:
 [[[ 3  8  4]
  [ 5 10 10]
  [ 3  9  6]]

 [[ 6  4  6]
  [ 3  9  3]
  [ 5  2  5]]

 [[ 6  1  2]
  [ 4  5  2]
  [ 9  2  3]]]
Soma Total:
 135
Soma acumulativa:
 [  3  11  15  20  30  40  43  52  58  64  68  74  77  86  89  94  96 101
 107 108 110 114 119 121 130 132 135]


In [4]:
import numpy as np
minha_lista = [6, 7, 0, 1.2, 10]
arr1 = np.array(minha_lista)
arr1

array([ 6. ,  7. ,  0. ,  1.2, 10. ])

In [5]:
import numpy as np
lista_de_listas = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(lista_de_listas)
arr2

array([[1, 2, 3],
       [4, 5, 6]])